# Generated by Django 5.0 on 2024-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
