# Generated by Django 5.0 on 2024-01-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept_product',
            name='name',
        ),
    ]
